# Site settings
title: Christo Goosen
description: 'CTO/Dev/DevOPS/Infosec/OWASP/BSides/Photogrtapher - Personal website, resume and blog. \n Bsuiness website: https://www.anomaloustech.co.za'
url: 'http://www.christogoosen.co.za'
baseurl: ''
google_analytics: 'UA-113874906-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Christo Goosen'
  email: christogoosen@gmail.com
  twitter_username: crypticG00se
  github_username:  c-goosen
  linkedin_username:  christo-goosen
  instagram_username: goosenaroundphoto

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
remote_theme: joshgerdes/jekyll-uno
