# Site settings
title: Christo Goosen
description: 'DevSecOps Lead at Utility Warehouse. Hacker, builder & entrepreneur. BSides Cape Town organiser | MSc Computer Science | Pentesting, Kubernetes security & vulnerability management.'
url: 'https://www.christogoosen.co.za'
baseurl: ''
google_analytics: 'UA-113874906-1'
google_tag_manager: 'G-3C6ZDSX2F2'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Christo Goosen'
  email: christogoosen@gmail.com
  twitter_username: crypticG00se
  github_username:  c-goosen
  linkedin_username:  christo-goosen
  instagram_username: goosenaroundphoto

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
remote_theme: joshgerdes/jekyll-uno
